# Generated by Django 5.2.1 on 2025-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphprefer',
            name='month',
        ),
        migrations.AddField(
            model_name='graphprefer',
            name='date_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
