# Generated by Django 5.2.1 on 2025-05-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_graphprefer_month_graphprefer_date_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphprefer',
            old_name='date_range',
            new_name='month',
        ),
    ]
