# Generated by Django 4.2.5 on 2025-05-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprefer', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
